# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BX3gs3dy490DoYSzkOaqmXFdC7-7MvJ5
"""

import pandas as pd

df_housing = pd.read_csv('Housing.csv')

"""Crear las tablas ETL

Tabla 1: Promedio de precio, tamaño, número de habitaciones por casa por código postal por año.
"""

df_avg_by_zip_year = df_housing.groupby(['zipcode', 'year']).agg(
    avg_price=('price', 'mean'),
    avg_area=('area', 'mean'),
    avg_bedrooms=('bedrooms', 'mean'),
    avg_bathrooms=('bathrooms', 'mean')
).reset_index()

"""Tabla 2: Precio promedio de casa por año y por código postal.


"""

df_avg_price_by_year_zip = df_housing.groupby(['year', 'zipcode'])['price'].mean().reset_index()
df_avg_price_by_year_zip.rename(columns={'price': 'avg_price'}, inplace=True)

"""Descargar Tablas para pasar a pasar Google Data Studio"""

df_avg_by_zip_year.to_csv('avg_by_zip_year.csv', index=False)
df_avg_price_by_year_zip.to_csv('avg_price_by_year_zip.csv', index=False)